---
openapi: 3.0.0
info:
  title: API Gateway
  description: API Gateway for micro services
  version: 1.0.0

servers:
  - url: http://127.0.0.1:5000

paths:
  /api/gateway/version:
    get:
      summary: Get the version
      description: Returns the gateway version.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
  /api/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string

  /api/user/{username}/exists:
    get:
      summary: Checks whether a username exists
      parameters:
        - name: username
          in: path
          description: username
          required: true
          schema:
            type: string
      response:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
definitions:
  Login:
    required:
    - username
    properties:
      username:
        type: string
      password:
        type: string
